FROM opensearchproject/logstash-oss-with-opensearch-output-plugin:latest

COPY ./config/logstash.conf /usr/share/logstash/pipeline/logstash.conf
COPY ./config/pipelines.yml /usr/share/logstash/config/pipelines.yml
