version: '3'

services:

# Infrastructure

  router:
    build: ./components/router/
    container_name: router
    volumes:
      - router_data:/opt/pocketsoc-ng/data
    cap_add:
      - NET_ADMIN
    volumes:
      - router_data:/opt/pocketsoc-ng/data
    networks:
      - internal
      - mirror


volumes:
  opensearch-data1:
  opensearch-data2:
  opensearch-dashboards:
  misp_mysql_data:
  misp_data:
  router_data:
  webserver_data:
  client_data:
  sshserver_data:
  zeek_data:
  certificates:
    external: true

networks:
  internal:
    ipam:
      config:
        - subnet: 172.18.0.0/16
  mirror:
    ipam:
      config:
        - subnet: 172.20.0.0/16
