FROM opensearchproject/opensearch-dashboards:latest

COPY ./config/opensearch_dashboards.yml /usr/share/opensearch-dashboards/config

CMD ["/usr/share/opensearch-dashboards/bin/opensearch-dashboards"]
