FROM cern/cs8-base

ENV ZEEK_VER 4.1.1
ENV PACKET_NAME zeek-af_packet-${ZEEK_VER}.tar.gz

ENV DIR /code
RUN mkdir ${DIR}
WORKDIR ${DIR}

ADD ./Zeek/build build
ADD ./Zeek/config config
ADD ./Zeek/scripts scripts
ADD ./Zeek/test test

RUN yum install -y bash git libmaxminddb libpcap openssl\
 python3 python3-devel python3-pip tcpdump && yum update\
 -y && yum clean all && rm -rf /var/cache/yum

RUN tar -zxvf build/${PACKET_NAME} -C /
RUN ln -s /usr/local/zeek-${ZEEK_VER}/logs /var/log/zeek
RUN ln -s /usr/local/zeek-${ZEEK_VER} /usr/local/zeek
env PATH /usr/local/zeek/bin/:$PATH
RUN /bin/sh scripts/configure.sh ${DIR} ${ZEEK_VER}
# Todo: script to run instead of tail -f
CMD zeekctl deploy && tail -f /dev/null

